version: '3.8'
services:
  namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      - rocketmq
    command: sh mqnamesrv
  
  broker:
    image: apache/rocketmq:5.3.2
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    volumes:
      - ./conf/broker.conf:/home/rocketmq/rocketmq-5.3.2/conf/broker.conf
      - ./data/broker/store:/home/rocketmq/store
    depends_on:
      - namesrv
    networks:
      - rocketmq
    command: sh mqbroker --enable-proxy -c /home/rocketmq/rocketmq-5.3.2/conf/broker.conf
  
  proxy:
    image: apache/rocketmq:5.3.2
    container_name: rmqproxy
    networks:
      - rocketmq
    depends_on:
      - broker
      - namesrv
    ports:
      - 8080:8080
      - 8081:8081
    restart: on-failure
    volumes:
      - ./conf/rmq-proxy.json:/home/rocketmq/rocketmq-5.3.2/conf/rmq-proxy.json      
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy  -pc /home/rocketmq/rocketmq-5.3.2/conf/rmq-proxy.json -n rmqnamesrv:9876 -pm cluster
  
  console:
    image: apacherocketmq/rocketmq-dashboard:2.0.1
    container_name: rmqconsole
    networks:
      - rocketmq
    ports:
      - 8082:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876

networks:
  rocketmq:
    driver: bridge
